### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dajare** [we3geeks/j-j-connington_murder-in-the-maze#1]
Good job overall! Hopefully these won't take too long to fix...

Various:
- [x] c2 - the blockquote can be styled to match the scans; this should go into `local.css`:
    ```
    #chapter-2 blockquote{
        font-variant: all-small-caps;
    }
    ```
- [x]  c13 - `deus ex machina` is in MW, and should not have italics or language tags
- [x] colophon - you need to wrap your name in `<b epub:type="z3998:personal-name">...</b>`, just like the PG transcriber.
- [x] content.opf -
    - [x] **short description** could be shorter. `:)` I would suggest: "After twin brothers are found murdered in a maze, the local Chief Constable must solve the crimes." 
    - [x] **long desc** : I don't think the CC needs to "solve the murders", so much as to "solve the mystery of their deaths", no?
    - [x] the production note can be simply eliminated; the change from `4.5` -> `4:05` is correctly "[Editorial]", but the way it was originally printed was simply the (British) convention for what we recognize as "4:05", so no need for the note.
    - [x] the author's wiki link should simply point to `https://en.wikipedia.org/wiki/Alfred_Walter_Stewart`

Both of these commits are "[Editorial]", so a **rebase** to rename them is needed (simply replace `Linting` with `[Editorial]` will do):
- [x] 1341cd5 - song titles commit
- [x] 01c2682 - "ABC" commit

**Comment by we3geeks** [comment]
Rebased to categorize two commits as editorial changes and pushed:
- https://github.com/we3geeks/j-j-connington_murder-in-the-maze/commit/b803707e4e3d4328e0a6c36ba1761dc61504b0fb (was `1341cd5`)
- https://github.com/we3geeks/j-j-connington_murder-in-the-maze/commit/b14ef9ab98b8b83ae456e8917bc3a60c5ab653e3 (was `01c2682`)

**Comment by we3geeks** [comment]
Addressed review items:
- https://github.com/we3geeks/j-j-connington_murder-in-the-maze/commit/3a104042558c279188bacabaa5db14fb61d5924e - chapter-2: style blockquote to match scans
- https://github.com/we3geeks/j-j-connington_murder-in-the-maze/commit/cdcf8789d503f8b96d980887fc41ec3c62e0e030 - colophon: wrap producer name with needed semantics
- https://github.com/we3geeks/j-j-connington_murder-in-the-maze/commit/d715ec262a094fd884c02e95d300264a5b7c3c73 - content.opf: address multiple review items

@dajare Should the commit for the change to chapter 13 be characterized as an editorial change as we are removing the italics?

**Comment by dajare** [comment]
Looking good, @we3geeks :) No, the c13 change is not "editorial" since there's no _material_ change to the text (nothing added, taken away, or textually altered); it's simply a matter of formatting.

**Comment by we3geeks** [comment]
Addressed review item:
- https://github.com/we3geeks/j-j-connington_murder-in-the-maze/commit/f337a4cc04537db95cbdc3fc8f44241da9ef9c5e - chapter-13: remove italics and semantics from "deus ex machina"

**Comment by dajare** [comment]
Nice - looks like we're all done. Now it's over to Alex; I'll flag in Google Groups. Looks like you're fairly happy in git, anyway!

**Comment by we3geeks** [comment]
RE git: yeah, recently-retired software developer.

Thanks for the review and help.

**Comment by dajare** [comment]
If you're minded to do some more SE productions (hope so!), and you enjoy mysteries, there are a number of "[Haycraft-Queen Cornerstones](https://www.sudalyph.org/seci/hq.php)" that have transcriptions and could make good 2nd, 3rd etc. projects. That link is a convenient way of seeing what's available. FWIW!

**Comment by we3geeks** [comment]
I'm definitely planning on doing more. Thanks for the pointer to that list; I recognize several there. 

The SE project feels like a great intersection of my professional experience and my love of reading. While I've been working on this book, I've done a bit of poking on other books by the same author which have crossed into the public domain (some that continue with this same lead character, and others that don't) and I'm leaning toward proposing a couple of those as my next project or two to continue to get my feet under me on the production process before I start venturing out a bit more.
